name: todo
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.6

dependencies:
  animated_splash_screen: ^1.3.0
  bloc: ^8.1.0
  cloud_firestore: ^4.0.4
  firebase_auth: ^4.1.0
  firebase_core: ^2.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.2.1
  form_field_validator: ^1.1.0
  form_validator: ^1.0.3
  intl: ^0.17.0
  lottie: ^1.4.3
  motion_toast: ^2.5.3
  uuid: ^3.0.6

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
